### ISSUE TITLE
warning/error if output file already exists

### ISSUE THREAD

**Issue by csjalbert** [boppingshoe/magma.gsi#11]
@boppingshoe , what are your thoughts on a check to make sure you don't overwrite an existing magma run? For example, I did a test and accidentally used the same file name as an existing dataset, which overwrote real data.  What about something like this at the top of `magmatize_data` :

`if (file.exists(file)) {
    stop("Output file already exists. Choose a different file name.")
  }
`

**Comment by boppingshoe** [comment]
added error check for existing magma_data file at the top of `magmatize_data`

**Comment by boppingshoe** [comment]
also added to `magmatize_summ()` if there are old trace histories in the folder
