### ISSUE TITLE
individual assignment data

### ISSUE THREAD

**Issue by csjalbert** [boppingshoe/magma.gsi#4]
@boppingshoe , this came up again, so I figured I'd add a note. 

At some point this winter it may be useful to look at feasibility of tracking IA data with MAGMA. It does not need to be turned on in all cases, but maybe a flag where you can turn on saving IA? In short, there are a few projects where folks may be interested in this but stuff like TBR, etc., it's not at all necessary. It's mainly smaller projects where it's been brought up, so that may be helpful for RAM usage. Also, if it's a huge task or not possible, we can come up with plan B..._run rubias and use those IAs, and call it close enough?_

**Comment by boppingshoe** [comment]
note to self: exclude burn-in's in the calculation

**Comment by boppingshoe** [comment]
done for now, until fire alarms....
