### ISSUE TITLE
rename functions

### ISSUE THREAD

**Issue by csjalbert** [boppingshoe/magma.gsi#6]
@boppingshoe , what are your thoughts on renaming the functions (and anything else) that are TBR specific? For example, the `magmatize_sum_tbr`'s are really just functions to deal with large datasets. Having generic names may help avoid confusion when implementing this elsewhere (e.g., BB). 

could be something simple like magmatize_summ_step1, step2, step3, etc

**Comment by boppingshoe** [comment]
Oh yeah good idea

Bobby Hsu
Biometrician II
(907) 267-2140
***@***.******@***.***>

From: Chase Jalbert ***@***.***>
Sent: Wednesday, June 14, 2023 10:07 AM
To: boppingshoe/magma.gsi ***@***.***>
Cc: Hsu, Bobby (DFG) ***@***.***>; Mention ***@***.***>
Subject: [boppingshoe/magma.gsi] rename functions (Issue #6)


CAUTION: This email originated from outside the State of Alaska mail system. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@boppingshoe<https://github.com/boppingshoe> , what are your thoughts on renaming the functions (and anything else) that are TBR specific? For example, the magmatize_sum_tbr's are really just functions to deal with large datasets. Having generic names may help avoid confusion when implementing this elsewhere (e.g., BB).

could be something simple like magmatize_summ_step1, step2, step3, etc

-

**Comment by csjalbert** [comment]
Closing as it looks like you completed this.
