### ISSUE TITLE
pop_prop_all naming consistency

### ISSUE THREAD

**Issue by csjalbert** [boppingshoe/magma.gsi#7]
Hey @boppingshoe , the `_all` outputs follow a different naming pattern than the weekly outputs (e.g., `age_prop`, `pop_prop`). Wondering if you should change is so that it's Dxxx_SubDxx, rather than xxx.xx or is there a reason for the difference?

**Comment by csjalbert** [comment]
Hey @boppingshoe , I found something else that could be standardized. The model summary contains a list object with 6 entries when summarized for pop and age. `$age_prop`  uses the term `grpvec`, while everything else uses `group`. Can you change this to `group` for consistency?

**Comment by boppingshoe** [comment]
nobody complains about the new naming scheme. close for now
