### ISSUE TITLE
FST package

### ISSUE THREAD

**Issue by csjalbert** [boppingshoe/magma.gsi#8]
Hey @boppingshoe , I'm wondering if we can incorporate [fst](https://www.fstpackage.org/) into the model summary. The summary steps require a lot of RAM for larger projects (e.g., TBR) and this package looks interesting.  I'm particularly interested in the section titled "Random access".

The current code stores the entire MAGMA output in RAM and I only summarize a single district at a time. I think you could add an `"all"` or (`1:3`) option to `district = ` in `magmatize_summ()` and have `fst` run through each district in the background. This is similar to what I do manually (i.e., 1 district at a time) but the difference is you're not storing everything in RAM. 

`magmatize_summ(ma_out = magma_out, ma_dat = magma_data, summ_level = "district", type = NULL, district = "all")`

This "all" idea may even work for the `type =` and `summ_level =` arguments, where you only read in what's required for the summary.

**Comment by boppingshoe** [comment]
done. saved a little RAM by loading one district at a time using `Fst`. But the biggest RAM used is the summary operations. I did my best to make it more efficient in the last update of the package
